module edu.ntnu.idi.bidata.idatg2003mappe {
  requires javafx.controls;
  requires javafx.fxml;
  requires javafx.web;

  requires org.controlsfx.controls;
  requires com.dlsc.formsfx;
  requires net.synedra.validatorfx;
  requires org.kordamp.ikonli.javafx;
  requires org.kordamp.bootstrapfx.core;
  requires eu.hansolo.tilesfx;
  requires com.almasb.fxgl.all;
  requires com.google.gson;
  requires com.opencsv;
  requires annotations;
  requires java.logging;
  opens edu.ntnu.idi.bidata.idatg2003mappe to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe;
  exports edu.ntnu.idi.bidata.idatg2003mappe.map;
  opens edu.ntnu.idi.bidata.idatg2003mappe.map to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.filehandling;
  opens edu.ntnu.idi.bidata.idatg2003mappe.filehandling to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.filehandling.game;
  opens edu.ntnu.idi.bidata.idatg2003mappe.filehandling.game to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.map.board;
  opens edu.ntnu.idi.bidata.idatg2003mappe.map.board to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.filehandling.exceptionhandling;
  opens edu.ntnu.idi.bidata.idatg2003mappe.filehandling.exceptionhandling to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.filehandling.map;
  opens edu.ntnu.idi.bidata.idatg2003mappe.filehandling.map to javafx.fxml, com.google.gson;
  exports edu.ntnu.idi.bidata.idatg2003mappe.entity.die;
  opens edu.ntnu.idi.bidata.idatg2003mappe.entity.die to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.entity.player;
  opens edu.ntnu.idi.bidata.idatg2003mappe.entity.player to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.app.boardgameselector;
  opens edu.ntnu.idi.bidata.idatg2003mappe.app.boardgameselector to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.app.playersetup;
  opens edu.ntnu.idi.bidata.idatg2003mappe.app.playersetup to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.app.missingdiamond.model;
  opens edu.ntnu.idi.bidata.idatg2003mappe.app.missingdiamond.model to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.app.missingdiamond.controller;
  opens edu.ntnu.idi.bidata.idatg2003mappe.app.missingdiamond.controller to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.app.missingdiamond.ui;
  opens edu.ntnu.idi.bidata.idatg2003mappe.app.missingdiamond.ui to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.app.missingdiamond.service;
  opens edu.ntnu.idi.bidata.idatg2003mappe.app.missingdiamond.service to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.app.common.ui;
  opens edu.ntnu.idi.bidata.idatg2003mappe.app.common.ui to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.app.common.observer;
  opens edu.ntnu.idi.bidata.idatg2003mappe.app.common.observer to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.app.laddergame.controller;
  opens edu.ntnu.idi.bidata.idatg2003mappe.app.laddergame.controller to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.app.laddergame.ui;
  opens edu.ntnu.idi.bidata.idatg2003mappe.app.laddergame.ui to javafx.fxml;
  exports edu.ntnu.idi.bidata.idatg2003mappe.app.laddergame.model;
  opens edu.ntnu.idi.bidata.idatg2003mappe.app.laddergame.model to javafx.fxml;
}